In [1]:
import tensorflow as tf
import numpy as np


In [2]:
# to print the value of tf.constant,tf.placeholder and tf.Variable
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.placeholder(tf.float32,shape=[2,3])
c = tf.Variable(tf.zeros([784,10]))

In [5]:
print type(a)
print a._shape

sess = tf.Session()
# for constant
print sess.run(a)
index1 =  sess.run(tf.argmax(a,axis=0)) # axis=0 means we search for max argument in each column
print index1,type(index1)
index2 = sess.run(tf.argmax(a,axis=1)) # axis=1 means we search for max argument in each row
print index2,type(index2)

print a.eval(session = sess)
print a.get_shape()
print type(a)

<class 'tensorflow.python.framework.ops.Tensor'>
(2, 3)
(2, 3)
[[ 1.  2.  3.]
 [ 4.  5.  6.]]
[1 1 1] <type 'numpy.ndarray'>
[2 2] <type 'numpy.ndarray'>
[[ 1.  2.  3.]
 [ 4.  5.  6.]]
(2, 3)
<class 'tensorflow.python.framework.ops.Tensor'>


In [6]:
print type(b)
print b._shape
print b.shape

# for  placeholder it must have a feed_dict
_b = np.array([[1,2,3],[9,6,7]])
print sess.run(b, feed_dict={b:_b})
print b.eval(session = sess, feed_dict={b:_b})
# every time we evaluate a node with connection to placeholders we need feed_dict to assign value to placeholders
print sess.run(tf.argmax(b,1),feed_dict={b:_b})
print b.get_shape()
print type(b)

<class 'tensorflow.python.framework.ops.Tensor'>
(2, 3)
(2, 3)
[[ 1.  2.  3.]
 [ 9.  6.  7.]]
[[ 1.  2.  3.]
 [ 9.  6.  7.]]
[2 0]
(2, 3)
<class 'tensorflow.python.framework.ops.Tensor'>


In [9]:
print type(c)
#print c._shape
#print c.shape
print c.get_shape()

# for variable must be initialized before evaluation
sess.run(tf.global_variables_initializer())
print sess.run(c)
print c.eval(session = sess)
print c.get_shape()
print type(c)

<class 'tensorflow.python.ops.variables.Variable'>
(784, 10)
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
(784, 10)
<class 'tensorflow.python.ops.variables.Variable'>


In [16]:
# Variable:Creation, Initialization, Saving, and Loading
# When you create a Variable you pass a Tensor as its initial value to the Variable() constructor. 
# TensorFlow provides a collection of ops that produce tensors often used for initialization 

d = tf.zeros(shape=[3,4])
print sess.run(d)

e = tf.ones_like(a)
print sess.run(e)

# zeros and ones fill the tensor with value 1 and 0.Use fill to customize if needed.
f = tf.fill([2,3],5.0)
print sess.run(f)

g = tf.constant(value = [1,2,3,4,5,6,7],shape = [3,3])
print sess.run(g)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 5.  5.  5.]
 [ 5.  5.  5.]]
[[1 2 3]
 [4 5 6]
 [7 7 7]]


In [36]:
# Create a tensor of shape [2, 3] consisting of random normal values, with mean
# -1 and standard deviation 4.
norm = tf.random_normal([2, 3], mean=-1, stddev=4)

# Shuffle the first dimension of a tensor
h = tf.constant([[1, 2], [3, 4], [5, 6]])
shuff = tf.random_shuffle(h)

# Each time we run these ops, different results are generated
sess = tf.Session()
# print(sess.run(shuff))
# print(sess.run(norm))
# print(sess.run(norm))

# Set an op-level seed to generate repeatable sequences across sessions.
norm1 = tf.random_normal([2, 3], seed=1234)
norm2 = tf.random_normal([2, 3], seed=12)
with tf.Session() as sess1:
    print(sess1.run(norm1))
    print(sess1.run(norm2))
    # print(sess1.run(norm1))
with tf.Session() as sess2:
    print(sess2.run(norm1))
#     print(sess2.run(norm1))
    print(sess2.run(norm2))

[[-0.12297685 -0.76935077 -0.13165176]
 [ 0.08304895 -3.00150084  0.79198867]]
[[-0.70187312 -2.94682765 -0.81546104]
 [-0.31579658 -0.44493788 -1.39343894]]
[[-0.12297685 -0.76935077 -0.13165176]
 [ 0.08304895 -3.00150084  0.79198867]]
[[ 0.39468181 -0.66613299  0.10462498]
 [ 2.39643908  0.59225196 -0.90378785]]
[[-0.70187312 -2.94682765 -0.81546104]
 [-0.31579658 -0.44493788 -1.39343894]]


In [39]:
i = tf.random_normal([2,3])
print sess.run(i)
print type(i)

<class 'tensorflow.python.framework.ops.Tensor'>
[[ 1.37556887 -1.13774085  0.44865981]
 [-0.54220235  0.89803177  1.83679056]]
<class 'tensorflow.python.framework.ops.Tensor'>


In [3]:
# Use random uniform values in [0, 1) as the initializer for a variable of shape
# [2, 3]. The default type is float32.
# var = tf.Variable(tf.random_uniform([2, 3]), name="var")
var = tf.Variable(tf.truncated_normal([2, 3]), name="var")
print type(var)
init = tf.global_variables_initializer()
print type(init)

sess = tf.Session()
print type(sess)
sess.run(init)
print var
print(sess.run(var))
print type(var)

<class 'tensorflow.python.ops.variables.Variable'>
<class 'tensorflow.python.framework.ops.Operation'>
<class 'tensorflow.python.client.session.Session'>
Tensor("var_1/read:0", shape=(2, 3), dtype=float32)
[[-0.62576127  0.4534632   0.66331804]
 [-0.07630707 -0.07772286 -0.45950451]]
<class 'tensorflow.python.ops.variables.Variable'>


In [46]:
# the shape of scalar is () 
j = tf.constant(1)
k = tf.constant([1])
print sess.run(j)
print k.eval(session=sess)
print j.get_shape()
print k.get_shape()

1
[1]
()
(1,)
