In [1]:
import tensorflow as tf
import numpy as np


In [2]:
# to print the value of tf.constant,tf.placeholder and tf.Variable
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.placeholder(tf.float32,shape=[2,3])
c = tf.Variable(tf.zeros([784,10]))

In [3]:
sess = tf.Session()
# for constant
print sess.run(a)
print a.eval(session = sess)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [5]:
# for  placeholder it must have a feed_dict
_b = np.array([[1,2,3],[5,6,7]])
print sess.run(b, feed_dict={b:_b})
print b.eval(session = sess, feed_dict={b:_b})

[[ 1.  2.  3.]
 [ 5.  6.  7.]]
[[ 1.  2.  3.]
 [ 5.  6.  7.]]


In [9]:
# for variable must be initialized before evaluation
sess.run(tf.global_variables_initializer())
print sess.run(c)
print c.eval(session = sess)

[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
