In [1]:
import tensorflow as tf
import numpy as np


In [2]:
# to print the value of tf.constant,tf.placeholder and tf.Variable
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.placeholder(tf.float32,shape=[2,3])
c = tf.Variable(tf.zeros([784,10]))

## constant

In [3]:
print type(a) # Tensor
# use a._shape in version before TF1.0 , use a.shape after
print a.shape # (2,3) but a is not tuple
print type(a.shape) # Tensorshape
print type(a.shape[0]) # Dimension

# sess = tf.Session()
sess = tf.InteractiveSession() # this is default session using InteractiveSession()
# for constant
print sess.run(a)
index1 =  sess.run(tf.argmax(a,axis=0)) # axis=0 means we search for max argument in each column
print index1,type(index1)
index2 = sess.run(tf.argmax(a,axis=1)) # axis=1 means we search for max argument in each row
print index2,type(index2)

# print a.eval(session = sess)
print a.eval()
print a.get_shape()
print type(a)

<class 'tensorflow.python.framework.ops.Tensor'>
(2, 3)
<class 'tensorflow.python.framework.tensor_shape.TensorShape'>
<class 'tensorflow.python.framework.tensor_shape.Dimension'>
[[ 1.  2.  3.]
 [ 4.  5.  6.]]
[1 1 1] <type 'numpy.ndarray'>
[2 2] <type 'numpy.ndarray'>
[[ 1.  2.  3.]
 [ 4.  5.  6.]]
(2, 3)
<class 'tensorflow.python.framework.ops.Tensor'>


## placeholder

In [4]:
print type(b)
# print b._shape
print b.shape

# for  placeholder it must have a feed_dict
_b = np.array([[1,2,3],[9,6,7]])
print sess.run(b, feed_dict={b:_b})
print b.eval(session = sess, feed_dict={b:_b})
# every time we evaluate a node with connection to placeholders we need feed_dict to assign value to placeholders
print sess.run(tf.argmax(b,1),feed_dict={b:_b})
print b.get_shape()
print type(b)

<class 'tensorflow.python.framework.ops.Tensor'>
(2, 3)
[[ 1.  2.  3.]
 [ 9.  6.  7.]]
[[ 1.  2.  3.]
 [ 9.  6.  7.]]
[2 0]
(2, 3)
<class 'tensorflow.python.framework.ops.Tensor'>


## Variable

In [5]:
print type(c)
#print c._shape
#print c.shape
print type(c.get_shape()) # TensorShape
print type(c.get_shape()[0]) # Dimension
shape = c.get_shape().as_list()
print type(shape) # list


# for variable must be initialized before evaluation
sess.run(tf.global_variables_initializer())
print sess.run(c)
# print c.eval(session = sess)
print c.eval()
print c.get_shape()
print type(c)
print type(sess.run(c))

<class 'tensorflow.python.ops.variables.Variable'>
<class 'tensorflow.python.framework.tensor_shape.TensorShape'>
<class 'tensorflow.python.framework.tensor_shape.Dimension'>
<type 'list'>
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
(784, 10)
<class 'tensorflow.python.ops.variables.Variable'>
<type 'numpy.ndarray'>


In [6]:
# Variable:Creation, Initialization, Saving, and Loading
# When you create a Variable you pass a Tensor as its initial value to the Variable() constructor. 
# TensorFlow provides a collection of ops that produce tensors often used for initialization 

d = tf.zeros(shape=[3,4])
print sess.run(d)

e = tf.ones_like(a)
print sess.run(e)

# zeros and ones fill the tensor with value 1 and 0.Use fill to customize if needed.
f = tf.fill([2,3],5.0)
print sess.run(f)

g = tf.constant(value = [1,2,3,4,5,6,7],shape = [3,3])
print sess.run(g)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 5.  5.  5.]
 [ 5.  5.  5.]]
[[1 2 3]
 [4 5 6]
 [7 7 7]]


In [7]:
# Create a tensor of shape [2, 3] consisting of random normal values, with mean
# -1 and standard deviation 4.
norm = tf.random_normal([2, 3], mean=-1, stddev=4)

# Shuffle the first dimension of a tensor
h = tf.constant([[1, 2], [3, 4], [5, 6]])
shuff = tf.random_shuffle(h)

# Each time we run these ops, different results are generated
sess = tf.Session()
# print(sess.run(shuff))
# print(sess.run(norm))
# print(sess.run(norm))

# Set an op-level seed to generate repeatable sequences across sessions.
norm1 = tf.random_normal([2, 3], seed=1234)
norm2 = tf.random_normal([2, 3], seed=12)
with tf.Session() as sess1:
    print(sess1.run(norm1))
    print(sess1.run(norm2))
    # print(sess1.run(norm1))
with tf.Session() as sess2:
    print(sess2.run(norm1))
#     print(sess2.run(norm1))
    print(sess2.run(norm2))

[[ 0.51340485 -0.25581399  0.65199131]
 [ 1.39236379  0.37256798  0.20336303]]
[[-0.43663138  0.8449775  -0.01180986]
 [-0.88440078 -0.18527539  0.21195167]]
[[ 0.51340485 -0.25581399  0.65199131]
 [ 1.39236379  0.37256798  0.20336303]]
[[-0.43663138  0.8449775  -0.01180986]
 [-0.88440078 -0.18527539  0.21195167]]


In [15]:
# i = tf.random_normal([1000,1000]) # the two sum cannot be even close
i = tf.ones([100,100]) # shows the scaling after dropout with the aim of keeping the sum unchanged
sum_i = tf.reduce_sum(tf.reduce_sum(i))
val,val_sum = sess.run([i,sum_i])
# print val 
print val_sum
# try dropout
_i = tf.nn.dropout(i,keep_prob=0.7)
sum_i2 = tf.reduce_sum(tf.reduce_sum(_i))
val2,val_sum2 = sess.run([_i,sum_i2],feed_dict={i:val})
# print val2
print val_sum2

10000.0
9994.22


In [13]:
# Use random uniform values in [0, 1) as the initializer for a variable of shape
# [2, 3]. The default type is float32.
# var = tf.Variable(tf.random_uniform([2, 3]), name="var")
var = tf.Variable(tf.truncated_normal([2, 3]), name="var")
print type(var)
init = tf.global_variables_initializer()
print type(init)

sess = tf.Session()
print type(sess)
sess.run(init)
print var
print(sess.run(var))
print type(var)

<class 'tensorflow.python.ops.variables.Variable'>
<class 'tensorflow.python.framework.ops.Operation'>
<class 'tensorflow.python.client.session.Session'>
Tensor("var/read:0", shape=(2, 3), dtype=float32)
[[ 0.11496793 -0.88963604  0.12979083]
 [-0.2623032  -1.23032916  0.01358601]]
<class 'tensorflow.python.ops.variables.Variable'>


In [46]:
# the shape of scalar is () 
j = tf.constant(1)
k = tf.constant([1])
print sess.run(j)
print k.eval(session=sess)
print j.get_shape()
print k.get_shape()

1
[1]
()
(1,)


In [24]:
# try tf.one_hot
m = tf.constant([1, 2, 3, 4, 5, 6], shape=[6, 1], name='a',dtype=tf.int32)
n = tf.one_hot(m-1,depth=6,on_value=1,off_value=0)
print sess.run(n)

[[[1 0 0 0 0 0]]

 [[0 1 0 0 0 0]]

 [[0 0 1 0 0 0]]

 [[0 0 0 1 0 0]]

 [[0 0 0 0 1 0]]

 [[0 0 0 0 0 1]]]
