In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf
import os
from os.path import join

In [2]:
##########################
## BUILD GRAPH
##########################
# reading from CSV files
path = os.getcwd()
# print(join(path,"data/read_file/file0.csv"))

filename_queue = tf.train.string_input_producer([join(path,"data/read_file/file0.csv"), 
                                                 join(path,"data/read_file/file1.csv"),
                                                 join(path,"data/read_file/file2.csv")],shuffle = True)

reader = tf.TextLineReader()
# print(type(reader))
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the decoded result.
record_defaults = [[1], [1], [1], [1], [1]]
col1, col2, col3, col4, col5 = tf.decode_csv(value, record_defaults=record_defaults)
features = tf.stack([col1, col2, col3, col4])
# print(type(features))

###################################################################################
# Thread body: loop until the coordinator indicates a stop was requested.
# If some condition becomes true, ask the coordinator to stop.
'''
def MyLoop(coord):
  while not coord.should_stop():
    ...do something...
    if ...some condition...:
      coord.request_stop()

# Main thread: create a coordinator.
coord = tf.train.Coordinator()

# Create 10 threads that run 'MyLoop()'
threads = [threading.Thread(target=MyLoop, args=(coord,)) for i in xrange(10)]

# Start the threads and wait for all of them to stop.
for t in threads:
  t.start()
coord.join(threads)
'''
####################################################################################

##############################
## RUN OPS
##############################
with tf.Session() as sess:
    coord = tf.train.Coordinator()
    # start_queue_runners return a list of threads
    # start populating the filename queue(equals to the for t in threads:t.shatrt() loop in demo in comments above)
    # You must call tf.train.start_queue_runners to populate the queue before you call run or eval to execute the 
    # read. Otherwise read will block while it waits for filenames from the queue
    threads = tf.train.start_queue_runners(sess = sess,coord=coord)
    
    print(len(threads))

    for i in range(36):
        # Retrieve a single instance:
        example, label = sess.run([features, col5])
        print(example,label)

    coord.request_stop()
    # Wait for all the threads to terminate.
    coord.join(threads)

2
[5 2 1 1] 1
[ 8 32 13  2] 2
[10  6 35 66] 3
[  7 123 345  14] 1
[ 2 31 23 12] 2
[  4  12 123   1] 3
[11 12 13 13] 1
[21 22 23 24] 2
[31 32 33 24] 3
[  7 123 345  14] 1
[ 2 31 23 12] 2
[  4  12 123   1] 3
[11 12 13 13] 1
[21 22 23 24] 2
[31 32 33 24] 3
[5 2 1 1] 1
[ 8 32 13  2] 2
[10  6 35 66] 3
[5 2 1 1] 1
[ 8 32 13  2] 2
[10  6 35 66] 3
[11 12 13 13] 1
[21 22 23 24] 2
[31 32 33 24] 3
[  7 123 345  14] 1
[ 2 31 23 12] 2
[  4  12 123   1] 3
[5 2 1 1] 1
[ 8 32 13  2] 2
[10  6 35 66] 3
[  7 123 345  14] 1
[ 2 31 23 12] 2
[  4  12 123   1] 3
[11 12 13 13] 1
[21 22 23 24] 2
[31 32 33 24] 3
