In [19]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf
import os
from os.path import join

In [27]:
# reading from CSV files
path = os.getcwd()
# print(join(path,"data/read_file/file0.csv"))

filename_queue = tf.train.string_input_producer([join(path,"data/read_file/file0.csv"), 
                                                 join(path,"data/read_file/file1.csv")])

reader = tf.TextLineReader()
# print(type(reader))
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the decoded result.
record_defaults = [[1], [1], [1], [1], [1]]
col1, col2, col3, col4, col5 = tf.decode_csv(value, record_defaults=record_defaults)
features = tf.stack([col1, col2, col3, col4])
# print(type(features))


with tf.Session() as sess:
    # start populating the filename queue
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(coord=coord)

    for i in range(6):
        # Retrieve a single instance:
        example, label = sess.run([features, col5])
        print(example,label)

    coord.request_stop()
    coord.join(threads)

<class 'tensorflow.python.framework.ops.Tensor'>
[  7 123 345  14] 1
[ 2 31 23 12] 2
[  4  12 123   1] 3
[11 12 13 13] 1
[21 22 23 24] 2
[31 32 33 24] 3
